# action.yml
name: 'Endpoint check'
author: '3sky'
description: 'Wrapper on wget and jq for make response validation'
branding:
  icon: 'check-square'
  color: 'white'
inputs:
  hostname:
    description: 'Hostname to check'
    required: true
    default: 'my-json-server.typicode.com'
  path:
    description: 'Path of endpoint'
    required: true
    default: '/typicode/demo/db'
  filter:
    description: 'jq filter'
    required: true
    default: '.profile.name'
  expected:
    description: 'Expected value from request'
    required: true
    default: 'typicode'
  unsecure:
    description: 'Skip certification validation'
    required: false
    default: false
outputs:
  result:
    description: 'Result of check'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.hostname }}
    - ${{ inputs.path }}
    - ${{ inputs.filter }}
    - ${{ inputs.expected }}
    - ${{ inputs.unsecure }}

